# Generated by Django 4.0.5 on 2022-09-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='Image_Link',
            field=models.ImageField(default='', max_length=3000, upload_to=''),
        ),
    ]
